//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppoDetail
    {
        public int Appo_Id { get; set; }
        public Nullable<int> Doc_Id { get; set; }
        public string Appo_Date { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public string User_Id { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public string Appo_Hospital { get; set; }
    }
}
