//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EHealthCareEntities : DbContext
    {
        public EHealthCareEntities()
            : base("name=EHealthCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DoctorsDetail> DoctorsDetails { get; set; }
        public DbSet<HospitaMaster> HospitaMasters { get; set; }
        public DbSet<MedicineDetail> MedicineDetails { get; set; }
        public DbSet<RoleDetail> RoleDetails { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<AppoDetail> AppoDetails { get; set; }
        public DbSet<PatientDetail> PatientDetails { get; set; }
        public DbSet<ReviewDetail> ReviewDetails { get; set; }
    }
}
