//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsDetail
    {
        public int Doc_Id { get; set; }
        public string Doc_Name { get; set; }
        public string Doc_Country { get; set; }
        public string Doc_State { get; set; }
        public string Doc_Hospital { get; set; }
        public string Doc_Specialist { get; set; }
        public string Doc_RegId { get; set; }
        public string Doc_Exp { get; set; }
        public string Doc_Details { get; set; }
        public string Doc_Home_Fee { get; set; }
        public string Doc_OnSite_Fee { get; set; }
        public bool IsActive { get; set; }
        public int User_Id { get; set; }
    }
}
