//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitaMaster
    {
        public int Hospital_Id { get; set; }
        public string Hospital_Name { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Hospital_Full_Address { get; set; }
        public string Hospital_Details { get; set; }
    }
}
