//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDetail
    {
        public int Med_Id { get; set; }
        public string Med_Name { get; set; }
        public string Med_Composition { get; set; }
        public string Med_Disease { get; set; }
        public Nullable<int> Med_Price { get; set; }
    }
}
