//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewDetail
    {
        public int Review_id { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Review_Text { get; set; }
        public string Review_Date { get; set; }
        public Nullable<int> Raised_By { get; set; }
        public string User_Role { get; set; }
    }
}
