//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Password { get; set; }
        public string User_Phone { get; set; }
        public string User_Mail { get; set; }
        public string User_Country { get; set; }
        public string User_Gender { get; set; }
        public string User_DOB { get; set; }
        public byte[] User_Photo { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
